export const GAME_GLOSSARY = {
  aura: { term: "Aura", category: "card-type", description: "A persistent support card that remains in the support field until removed." },
  font: { term: "Font", category: "zone-resource", description: "A card in the Font row. Ready Fonts are automatically exhausted to pay a card's cost. One hand card may be committed face-down as a basic Font each turn." },
  ready: { term: "Ready", category: "state", description: "Available to attack or pay an exhaust cost." },
  exhausted: { term: "Exhausted", category: "state", description: "Turned or marked as used and unavailable for actions that require a ready card until it readies." },
  swift: { term: "Swift", category: "keyword", description: "This creature may attack during the turn it is summoned." },
  guard: { term: "Guard", category: "keyword", description: "The opposing player cannot be attacked while they control a ready creature with Guard." },
  trample: { term: "Trample", category: "keyword", description: "Excess combat damage dealt to an enemy creature is dealt to that creature's controller." },
  power: { term: "Power", category: "stat", description: "The amount of combat damage a creature deals." },
  health: { term: "Health", category: "stat", description: "A creature is destroyed when marked damage equals or exceeds its Health. Health is the prototype term for toughness." },
  toughness: { term: "Toughness", category: "alias", description: "An authoring alias for Health; player-facing prototype cards use Health." },
  salvage: { term: "Salvage", category: "zone", description: "The public zone where detached equipment and unused consumables wait to be recovered." },
  boneyard: { term: "Boneyard", category: "zone", description: "The public discard zone for destroyed creatures and resolved cards." },
  mana: { term: "Mana", category: "resource", description: "A spendable resource generated by Fonts and used to pay card and ability costs." },
  reaction: { term: "Reaction", category: "timing", description: "An effect that may be played during an appropriate priority window." },
  priority: { term: "Priority", category: "timing", description: "Permission to take a reaction or pass. Two consecutive passes resolve the newest stack effect." },
  charges: { term: "Charges", category: "resource", description: "Uses remaining on a consumable; it enters the boneyard after its final charge is spent." },
  equip: { term: "Equip", category: "action", description: "Attach an item to a legal creature by paying its equip or recovery cost." },
} as const;

export type GlossaryKey = keyof typeof GAME_GLOSSARY;
export type GlossaryEntry = (typeof GAME_GLOSSARY)[GlossaryKey];
export const glossaryEntries: readonly GlossaryEntry[] = Object.values(GAME_GLOSSARY);
