import { describe, expect, it } from "vitest";
import { applyCommand, createGame, replayMatch, shuffle, type CardDefinition, type CommandRecord, type GameState, type Replay, type Transition } from "../src/index.js";

const defs: CardDefinition[] = [
  { id: "font", name: "Primal Well", type: "Font", fontMana: ["Primal"] },
  { id: "cub", name: "Briar Cub", type: "Creature", cost: { Generic: 1 }, power: 2, health: 2 },
  { id: "giant", name: "Moss Giant", type: "Creature", cost: { Generic: 1 }, power: 4, health: 4 },
  { id: "bolt", name: "Ember Dart", type: "Spell", cost: { Generic: 1 }, target: "any", effects: [{ op: "damage", amount: 3 }] },
  { id: "aura", name: "Wild Chorus", type: "Aura", cost: { Generic: 1 }, modifiers: { power: 1, health: 1 } },
  { id: "blade", name: "Glass Blade", type: "MagicItem", cost: { Generic: 1 }, equipCost: { Generic: 1 }, target: "creature", slot: "weapon", modifiers: { power: 2 } },
  { id: "potion", name: "Sun Draught", type: "Consumable", cost: { Generic: 1 }, recoveryCost: { Generic: 1 }, target: "any", charges: 2, effects: [{ op: "heal", amount: 2 }] },
  { id: "bomb", name: "Ash Phial", type: "Consumable", cost: { Generic: 1 }, target: "creature", charges: 1, exhaustBearer: true, effects: [{ op: "damage", amount: 4 }] },
  { id: "draw", name: "Remember", type: "Spell", effects: [{ op: "draw", amount: 1 }] },
];
const deck = Array.from({ length: 10 }, () => ["font", "cub", "giant", "bolt", "aura", "blade", "potion", "bomb", "draw"]).flat();
function game(hand = 36, life = 20): GameState { return createGame({ seed: 42, definitions: defs, players: [{ id: "p1", deck }, { id: "p2", deck }], startingHand: hand, startingLife: life }).state; }
function card(state: GameState, player: string, definition: string, zone = "hand"): string { return Object.values(state.cards).find((c) => c.owner === player && c.definitionId === definition && c.zone === zone)!.id; }
function command(state: GameState, input: Parameters<typeof applyCommand>[1]): Transition { return applyCommand(state, input); }
function resolve(state: GameState): GameState { state = command(state, { type: "PASS_PRIORITY", playerId: state.priorityPlayer }).state; return command(state, { type: "PASS_PRIORITY", playerId: state.priorityPlayer }).state; }
function mana(state: GameState, player = "p1", amount = 1): GameState { const p = state.players[player]!; return { ...state, players: { ...state.players, [player]: { ...p, mana: { ...p.mana, Generic: amount } } } }; }
function ready(state: GameState, id: string): GameState { return { ...state, cards: { ...state.cards, [id]: { ...state.cards[id]!, exhausted: false } } }; }

describe("determinism and setup", () => {
  it("shuffles identically with the same seed", () => { expect(shuffle(deck, 7)).toEqual(shuffle(deck, 7)); expect(shuffle(deck, 7)[0]).not.toEqual(shuffle(deck, 8)[0]); });
  it("draws starting hands deterministically", () => { expect(game(3)).toEqual(game(3)); expect(game(3).players.p1!.zones.hand).toHaveLength(3); });
  it("loses when required to draw from an empty deck", () => { let s = game(90); s = command(s, { type: "END_TURN", playerId: "p1" }).state; expect(s.result).toMatchObject({ loserId: "p2", reason: "deck" }); });
});

describe("fonts and mana", () => {
  it("commits one face-down Font per turn and generates generic mana", () => { let s = game(); const id = card(s, "p1", "bolt"); s = command(s, { type: "COMMIT_AS_FONT", playerId: "p1", cardId: id }).state; expect(s.cards[id]).toMatchObject({ zone: "fontRow", faceDown: true }); const t = command(s, { type: "ACTIVATE_FONT", playerId: "p1", fontId: id, manaType: "Generic" }); expect(t.state.players.p1!.mana.Generic).toBe(1); expect(t.events).toContainEqual(expect.objectContaining({ type: "MANA_GENERATED" })); expect(() => command(t.state, { type: "COMMIT_AS_FONT", playerId: "p1", cardId: card(t.state, "p1", "cub") })).toThrowError(/already/); });
  it("printed Fonts produce only their listed tradition", () => { let s = game(); const id = card(s, "p1", "font"); s = { ...s, cards: { ...s.cards, [id]: { ...s.cards[id]!, zone: "fontRow", faceDown: false } }, players: { ...s.players, p1: { ...s.players.p1!, zones: { ...s.players.p1!.zones, hand: s.players.p1!.zones.hand.filter((x) => x !== id), fontRow: [id] } } } }; expect(() => command(s, { type: "ACTIVATE_FONT", playerId: "p1", fontId: id, manaType: "Arcane" })).toThrow(); expect(command(s, { type: "ACTIVATE_FONT", playerId: "p1", fontId: id, manaType: "Primal" }).state.players.p1!.mana.Primal).toBe(1); });
  it("spends typed mana before generic payments", () => { let s = mana(game(), "p1", 1); const id = card(s, "p1", "cub"); s = command(s, { type: "PLAY_CARD", playerId: "p1", cardId: id }).state; expect(s.players.p1!.mana.Generic).toBe(0); expect(() => command(game(), { type: "PLAY_CARD", playerId: "p1", cardId: card(game(), "p1", "cub") })).toThrowError(/mana/); });
});

describe("stack, cards, combat and victory", () => {
  it("summons only after both players pass priority", () => { let s = mana(game()); const id = card(s, "p1", "cub"); s = command(s, { type: "PLAY_CARD", playerId: "p1", cardId: id }).state; expect(s.stack).toHaveLength(1); expect(s.priorityPlayer).toBe("p2"); s = resolve(s); expect(s.cards[id]!.zone).toBe("creatureField"); });
  it("rejects illegal spell targets", () => { const s = mana(game()); expect(() => command(s, { type: "PLAY_CARD", playerId: "p1", cardId: card(s, "p1", "bolt"), targets: ["missing"] })).toThrowError(/target/i); });
  it("resolves stack last-in-first-out", () => { let s = mana(game(), "p1", 2); const b1 = card(s, "p1", "bolt"); s = command(s, { type: "PLAY_CARD", playerId: "p1", cardId: b1, targets: ["p2"] }).state; s = mana(s, "p2", 1); const b2 = card(s, "p2", "bolt"); s = command(s, { type: "PLAY_CARD", playerId: "p2", cardId: b2, targets: ["p1"] }).state; s = resolve(s); expect(s.players.p1!.life).toBe(17); expect(s.players.p2!.life).toBe(20); });
  it("deals simultaneous creature combat damage and destroys lethal creatures", () => { let s = mana(game()); const a = card(s, "p1", "cub"); s = resolve(command(s, { type: "PLAY_CARD", playerId: "p1", cardId: a }).state); s = command(s, { type: "END_TURN", playerId: "p1" }).state; s = mana(s, "p2"); const d = card(s, "p2", "cub"); s = resolve(command(s, { type: "PLAY_CARD", playerId: "p2", cardId: d }).state); s = command(s, { type: "END_TURN", playerId: "p2" }).state; s = ready(s, a); s = resolve(command(s, { type: "ATTACK", playerId: "p1", attackerId: a, targetId: d }).state); expect(s.cards[a]!.zone).toBe("boneyard"); expect(s.cards[d]!.zone).toBe("boneyard"); });
  it("ends at zero life and on concession", () => { let s = mana(game(36, 3)); s = resolve(command(s, { type: "PLAY_CARD", playerId: "p1", cardId: card(s, "p1", "bolt"), targets: ["p2"] }).state); expect(s.result).toMatchObject({ winnerId: "p1", reason: "life" }); expect(command(game(), { type: "CONCEDE", playerId: "p1" }).state.result).toMatchObject({ winnerId: "p2", reason: "concession" }); });
});

describe("persistent cards and attachments", () => {
  function creatureOnField(): { state: GameState; creature: string } { let state = mana(game()); const creature = card(state, "p1", "giant"); state = resolve(command(state, { type: "PLAY_CARD", playerId: "p1", cardId: creature }).state); return { state, creature }; }
  it("creates an Aura with a continuous modifier", () => { let { state: s, creature } = creatureOnField(); s = mana(s); const aura = card(s, "p1", "aura"); s = resolve(command(s, { type: "PLAY_CARD", playerId: "p1", cardId: aura }).state); expect(s.cards[aura]!.zone).toBe("supportField"); s = { ...s, cards: { ...s.cards, [creature]: { ...s.cards[creature]!, damage: 4 } } }; expect(command(s, { type: "END_TURN", playerId: "p1" }).state.cards[creature]!.zone).toBe("creatureField"); });
  it("drops an item on bearer destruction and allows paid re-equipping", () => { let { state: s, creature } = creatureOnField(); s = mana(s); const item = card(s, "p1", "blade"); s = resolve(command(s, { type: "PLAY_CARD", playerId: "p1", cardId: item, targets: [creature] }).state); const killer = card(s, "p2", "bolt"); s = { ...s, activePlayer: "p2", priorityPlayer: "p2", players: { ...s.players, p2: { ...s.players.p2!, mana: { ...s.players.p2!.mana, Generic: 1 } } } }; s = resolve(command(s, { type: "PLAY_CARD", playerId: "p2", cardId: killer, targets: [creature] }).state); expect(s.cards[item]!.zone).toBe("supportField"); const killer2 = card(s, "p1", "bolt"); s = mana({ ...s, activePlayer: "p1", priorityPlayer: "p1" }); s = resolve(command(s, { type: "PLAY_CARD", playerId: "p1", cardId: killer2, targets: [creature] }).state); expect(s.cards[item]).toMatchObject({ zone: "salvageField" }); const second = card(s, "p1", "cub"); s = { ...s, cards: { ...s.cards, [second]: { ...s.cards[second]!, zone: "creatureField" } }, players: { ...s.players, p1: { ...s.players.p1!, mana: { ...s.players.p1!.mana, Generic: 1 }, zones: { ...s.players.p1!.zones, hand: s.players.p1!.zones.hand.filter((x) => x !== second), creatureField: [second] } } } }; s = command(s, { type: "EQUIP", playerId: "p1", itemId: item, creatureId: second }).state; expect(s.cards[item]!.attachedTo).toBe(second); });
  it("uses consumable charges and moves the final charge to boneyard after resolution", () => { let { state: s, creature } = creatureOnField(); s = mana(s); const potion = card(s, "p1", "potion"); s = resolve(command(s, { type: "PLAY_CARD", playerId: "p1", cardId: potion, targets: [creature] }).state); s = command(s, { type: "ACTIVATE_ABILITY", playerId: "p1", sourceId: potion, abilityId: "use", targets: ["p1"] }).state; expect(s.cards[potion]!.charges).toBe(1); s = resolve(s); s = command(s, { type: "ACTIVATE_ABILITY", playerId: "p1", sourceId: potion, abilityId: "use", targets: ["p1"] }).state; expect(s.cards[potion]!.charges).toBe(0); });
  it("salvages unused consumables when bearer dies", () => { let { state: s, creature } = creatureOnField(); s = mana(s); const bomb = card(s, "p1", "bomb"); s = resolve(command(s, { type: "PLAY_CARD", playerId: "p1", cardId: bomb, targets: [creature] }).state); s = { ...s, cards: { ...s.cards, [creature]: { ...s.cards[creature]!, damage: 1 } } }; const bolt = card(s, "p2", "bolt"); s = { ...s, activePlayer: "p2", priorityPlayer: "p2", players: { ...s.players, p2: { ...s.players.p2!, mana: { ...s.players.p2!.mana, Generic: 1 } } } }; s = resolve(command(s, { type: "PLAY_CARD", playerId: "p2", cardId: bolt, targets: [creature] }).state); expect(s.cards[bomb]!.zone).toBe("salvageField"); });
});

  it("reconstructs and verifies a command/event replay", () => { const initial = createGame({ seed: 42, definitions: defs, players: [{ id: "p1", deck }, { id: "p2", deck }], startingHand: 9 }); let s = initial.state; const records: CommandRecord[] = []; const c = { type: "CONCEDE", playerId: "p2" } as const; const transition = command(s, c); records.push({ command: c, events: transition.events }); s = transition.state; const replay: Replay = { seed: 42, players: [{ id: "p1", deck }, { id: "p2", deck }], startingLife: 20, startingHand: 9, commands: records, rulesVersion: "0.1.0" }; expect(replayMatch(replay, defs)).toEqual(s); });
