import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowDownRight, ArrowRight, CalendarDays, Check, Clock3, Compass, Copy, Flag, HandHeart, Leaf, MapPin, Plus, ShieldCheck, Sparkles, Target, Trophy, Users } from 'lucide-react';
import type { Command, Contribution, MiniCharacter, Snapshot, WestmarchEvent } from './model';
import { eventProgress, pendingAssessment, formatDuration } from './rules';
import { dateLabel } from './format';

export interface PageProps { snapshot: Snapshot; execute: (command: Command) => Promise<boolean>; busy: boolean }
export function BackLink() { return <Link className="wm-back" to="/westmarch"><ArrowDownRight size={16} /> Back to the event board</Link>; }
export function Help({ title, children }: { title: string; children: React.ReactNode }) { return <details className="wm-help"><summary><Sparkles size={15} />{title}</summary><div>{children}</div></details>; }

function Progress({ event, contributions }: { event: WestmarchEvent; contributions: Contribution[] }) {
  const progress = eventProgress(event, contributions);
  return <div className="wm-progress-block">
    <div className="wm-progress-label"><span>{progress.total ? `${progress.percentage?.toFixed(0)}% successful` : 'A story waiting to unfold'}</span><span>Target {event.definition.target}%</span></div>
    <div className="wm-progress" role="img" aria-label={`${progress.successes} successes, ${progress.failures} failures. Target ${event.definition.target} percent.`}>
      <span className="wm-progress-success" style={{ width: `${progress.percentage ?? 0}%` }} /><span className="wm-progress-failure" style={{ width: `${progress.total ? 100 - (progress.percentage ?? 0) : 0}%` }} />
      <span className="wm-progress-target" style={{ left: `${event.definition.target}%` }} />
    </div><p className="wm-fine">{progress.successes} successes · {progress.failures} failures · {event.definition.minimum} main checks needed</p>
  </div>;
}

export function EventBoard({ snapshot }: PageProps) {
  const active = snapshot.events.filter(e => ['active', 'paused'].includes(e.status));
  const completed = snapshot.events.filter(e => e.status === 'completed');
  const [region, setRegion] = useState('');
  const meta = active.find(e => e.definition.kind === 'meta');
  return <>
    <section className="wm-hero">
      <div className="wm-hero-copy"><p className="wm-kicker"><span className="wm-live-dot" /> THE WESTMARCH CHRONICLE</p><h1>Small acts.<br /><em>Lasting legends.</em></h1><p className="wm-lede">A field restored. A mystery unravelled. A town that remembers your name. Choose where your character makes a difference.</p>
        <div className="wm-actions"><Link className="wm-button" to="/westmarch/schedule"><CalendarDays size={18} /> Plan your contributions <ArrowRight size={16} /></Link><Link className="wm-text-link" to="/westmarch/characters">Meet your characters <ArrowRight size={16} /></Link></div>
        <div className="wm-hero-stats"><span><strong>{active.filter(e => e.definition.kind === 'minor').length}<small> / 5</small></strong> local stories unfolding</span><span><strong>{snapshot.characters.filter(c => c.status === 'active').length}</strong> characters in your company</span></div>
      </div><div className="wm-hero-art" aria-hidden="true"><div className="wm-orbit wm-orbit-one" /><div className="wm-orbit wm-orbit-two" /><div className="wm-orbit wm-orbit-three" /><div className="wm-star">✦</div><div className="wm-art-label">LEAVE THE WORLD<br />A LITTLE DIFFERENT</div><Compass className="wm-compass" strokeWidth={0.7} /></div>
    </section>
    <section className="wm-onboarding" aria-label="How participation works"><div><span>01</span><p><strong>Bring a character</strong>Start small. Their story grows with you.</p></div><div><span>02</span><p><strong>Make time to help</strong>One shared schedule across every event.</p></div><div><span>03</span><p><strong>Roll now. Change things later.</strong>Aid can improve your pending outcome.</p></div></section>
    <section className="wm-board-section"><div className="wm-section-heading"><div><p className="wm-kicker">CLOSER TO HOME</p><h2>Where will you lend a hand?</h2></div><label className="wm-filter"><MapPin size={16} /><span className="wm-sr-only">Filter by region</span><select value={region} onChange={e => setRegion(e.target.value)}><option value="">Every region</option>{[...new Set(active.map(e => e.definition.region))].sort().map(r => <option key={r}>{r}</option>)}</select></label></div>
      <div className="wm-event-grid">{snapshot.slots.filter(s => s.kind === 'minor').map(slot => {
        const event = snapshot.events.find(e => e.id === slot.eventId);
        if (event && region && event.definition.region !== region) return null;
        return event ? <article key={slot.id} className="wm-event-card"><div className="wm-card-top"><span className="wm-badge"><MapPin size={12} />{event.definition.region}</span><span className="wm-fine">{event.status === 'paused' ? 'On hold' : `STORY ${String(slot.id).padStart(2, '0')}`}</span></div><div className="wm-event-symbol"><Leaf size={27} strokeWidth={1.4} /></div><Link className="wm-card-title" to={`/westmarch/events/${event.id}`}><h3>{event.definition.title}</h3></Link><p className="wm-card-description">{event.definition.description}</p><Progress event={event} contributions={snapshot.contributions} /><div className="wm-card-bottom"><span><Clock3 size={14} />{event.endsAt ? `Until ${new Date(event.endsAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}` : 'Awaiting launch'}</span><Link to={`/westmarch/events/${event.id}`} aria-label={`Open ${event.definition.title}`}><ArrowRight size={20} /></Link></div></article>
          : <article key={slot.id} className="wm-empty-slot"><span className="wm-slot-number">0{slot.id}</span><Compass size={30} strokeWidth={1} /><h3>{slot.cooldownUntil && new Date(slot.cooldownUntil) > new Date() ? 'A moment of quiet' : 'Room for a new story'}</h3><p>{slot.cooldownUntil && new Date(slot.cooldownUntil) > new Date() ? `This slot rests until ${dateLabel(slot.cooldownUntil)}.` : 'The next approved event will begin here when it is ready.'}</p><span className="wm-fine">MINOR EVENT SLOT</span></article>;
      })}</div>
    </section>
    <section className="wm-meta-card"><div className="wm-meta-emblem"><Sparkles size={38} strokeWidth={1} /></div><div><p className="wm-kicker">ONE WORLD. A LARGER STORY.</p><h2>{meta?.definition.title ?? 'The next chapter is on the horizon.'}</h2><p>{meta?.definition.description ?? 'Meta events bring the whole Westmarch together. Event Staff will open the next chapter when the time is right.'}</p></div>{meta && <Link className="wm-button secondary" to={`/westmarch/events/${meta.id}`}>Explore the meta event <ArrowRight size={16} /></Link>}</section>
    <section className="wm-grid wm-board-section"><Link className="wm-feature-link" to="/westmarch/leaderboards"><Trophy size={25} /><div><p className="wm-kicker">THE PEOPLE WHO SHOWED UP</p><h3>Local legends</h3><p>Discover dedicated helpers, talented performers, and memorable rolls.</p></div><ArrowRight /></Link><Link className="wm-feature-link" to="/westmarch/submissions"><Flag size={25} /><div><p className="wm-kicker">GIVE YOUR SETTING A STORY</p><h3>Create an event</h3><p>Bring a region to life. Submit your idea for review and earn a creator code.</p></div><ArrowRight /></Link></section>
    {completed.length > 0 && <section className="wm-panel"><h2>Stories remembered</h2><div className="wm-stack">{completed.slice(0, 8).map(e => <Link className="wm-history-link" key={e.id} to={`/westmarch/events/${e.id}`}><span>{e.definition.title}</span><span className="wm-badge">{e.outcome?.replace(/_/g, ' ') ?? 'Completed'}</span><ArrowRight size={16} /></Link>)}</div></section>}
    <div className="wm-community"><HandHeart size={18} /><p>Help care for the stories we tell together.</p><Link to="/westmarch/staff/apply">Apply for Event Staff <ArrowRight size={14} /></Link>{snapshot.isStaff && <Link to="/westmarch/controls">Event Controls <ShieldCheck size={14} /></Link>}{snapshot.isAdmin && <Link to="/westmarch/admin">Staff administration</Link>}</div>
  </>;
}

export function EventDetail({ snapshot }: PageProps) {
  const { eventId } = useParams();
  const event = snapshot.events.find(e => e.id === eventId);
  const [copied, setCopied] = useState(false);
  if (!event) return <><BackLink /><section className="wm-empty"><h1>Event unavailable</h1><p>This event may be private, removed, or awaiting review.</p></section></>;
  const definition = event.definition;
  const contributions = snapshot.contributions.filter(c => c.eventId === event.id && c.status !== 'void');
  const participants = [...new Map(contributions.filter(c => c.status === 'completed').map(c => [c.characterId, c.characterName])).entries()];
  const completed = event.status === 'completed';
  return <><BackLink /><section className="wm-detail-hero"><div className="wm-actions"><span className="wm-badge"><MapPin size={13} />{definition.region}</span><span className="wm-badge">{definition.kind} event</span><span className="wm-badge">{event.status}</span></div><h1>{definition.title}</h1><p className="wm-lede">A request from {definition.requester}</p><div className="wm-actions"><span className="wm-fine"><Clock3 size={14} /> {event.endsAt ? `Ends ${dateLabel(event.endsAt)}` : `${formatDuration(definition.durationHours)} once launched`}</span><button className="wm-text-link" onClick={async () => { try { await navigator.clipboard.writeText(window.location.href); setCopied(true); } catch { setCopied(false); } }}>{copied ? <Check size={15} /> : <Copy size={15} />}{copied ? 'Link copied' : 'Copy event link'}</button></div></section>
    {event.status === 'paused' && <div className="wm-notice">This event is paused. New bookings and result processing are on hold. Existing work keeps its original scheduled times.</div>}
    {event.status === 'cancelled' && <div className="wm-notice">This event was removed. Completed history is preserved; unfinished contributions no longer reserve your character’s time.</div>}
    <div className="wm-detail-grid"><div className="wm-stack"><section className="wm-panel"><p className="wm-kicker">THE REQUEST</p><h2>A little help could change everything.</h2><p className="wm-prose">{definition.description}</p>{definition.location && <div className="wm-location"><MapPin size={19} /><div><strong>About this place</strong><p className="wm-prose">{definition.location}</p></div></div>}</section>
      <section className="wm-panel"><p className="wm-kicker">WAYS TO HELP</p><h2>Every contribution takes time.</h2><p className="wm-muted">Choose an approach, explain your action, and roll when you commit your schedule. Each action makes one check.</p><div className="wm-stack">{definition.actions.map(action => {
        const successes = contributions.filter(c => c.actionId === action.id && c.status === 'completed' && c.success).length;
        return <article className="wm-action-card" key={action.id}><div className="wm-section-heading"><h3>{action.kind === 'aid' ? <HandHeart size={18} /> : <Target size={18} />}{action.name}</h3><span className="wm-badge">{formatDuration(action.hours)}</span></div><p>{action.description}</p><div className="wm-actions">{action.skills.map(skill => <span className="wm-skill" key={skill}>{skill}</span>)}<span className="wm-fine">{action.kind === 'aid' ? 'Aid check' : 'Main contribution'} · DC adjustment {action.adjustment >= 0 ? '+' : ''}{action.adjustment}</span></div>{action.kind === 'aid' && <div className="wm-aid-track"><div className="wm-progress-label"><span>{Math.min(successes, action.threshold)} / {action.threshold} successes</span><strong>{successes >= action.threshold ? 'Unlocked' : 'Unlocks'}: main DC −{action.reduction}</strong></div><progress value={Math.min(successes, action.threshold)} max={action.threshold} /></div>}</article>;
      })}</div></section>
      <Help title="How aid can change a roll you have already made"><p>Your die and modifier stay fixed. Each completed aid track lowers main-check DCs. If aid unlocks before your scheduled action finishes, your pending failure can become a success. Several aid tracks stack together.</p><p>Only finished main checks affect the event’s success percentage. Aid does not make other aid checks easier.</p></Help>
    </div><aside className="wm-stack"><section className="wm-panel wm-sticky"><p className="wm-kicker">THE COMMUNITY’S EFFORT</p><h2>{completed ? 'The story is settled.' : 'Every result matters.'}</h2><Progress event={event} contributions={snapshot.contributions} /><p className="wm-muted">At least {definition.target}% of completed main checks must succeed, with a minimum of {definition.minimum} main checks by the deadline.</p><p className="wm-fine">{contributions.filter(c => c.status === 'pending').length} contributions still in progress</p>{event.status === 'active' && <Link className="wm-button wm-full" to={`/westmarch/schedule?event=${event.id}`}><CalendarDays size={17} /> Make time for this event</Link>}<Help title="Before you roll"><p>One day means 24 hours. All events share your character’s calendar. A committed roll cannot be cancelled or moved. Your entered modifier is recorded for staff review.</p><p>This release compares your total with the DC; natural 1s and 20s have no special effect. Reputation payouts are not configured yet.</p></Help></section></aside></div>
    {completed && <section className="wm-outcome"><Sparkles size={30} /><p className="wm-kicker">{event.outcome === 'success' ? 'A DIFFERENCE WORTH CELEBRATING' : 'A CHAPTER REMEMBERED'}</p><h2>{event.outcome === 'success' ? 'You helped write a brighter ending.' : 'The Westmarch remembers your efforts.'}</h2><p className="wm-prose">{event.outcome === 'success' ? definition.successText : definition.failureText}</p><div className="wm-actions">{participants.map(([id, name]) => <span key={id} className="wm-badge"><Users size={13} />{name}</span>)}</div></section>}
    <section className="wm-panel wm-board-section"><div className="wm-section-heading"><div><p className="wm-kicker">THE PEOPLE BEHIND THE PROGRESS</p><h2>Contribution journal</h2></div><span className="wm-badge">{contributions.length} attempts</span></div>{contributions.length ? <div className="wm-stack">{contributions.slice().sort((a, b) => b.endsAt.localeCompare(a.endsAt)).map(c => <RollRecord key={c.id} contribution={c} event={event} contributions={snapshot.contributions} />)}</div> : <div className="wm-empty"><Leaf size={27} /><h3>The first page is still blank.</h3><p>Be the first to make time for this community.</p></div>}</section>
  </>;
}

export function RollRecord({ contribution: c, event, contributions }: { contribution: Contribution; event: WestmarchEvent; contributions: Contribution[] }) {
  const assessment = pendingAssessment(c, event, contributions);
  const status = c.status === 'void' ? 'Voided' : c.status === 'completed' ? (c.success ? 'Completed · Success' : 'Completed · Failure') : assessment.state === 'potential' ? 'Has Potential' : assessment.state === 'success' ? 'Success · Pending' : 'Failure · Pending';
  return <article className="wm-roll-record"><div className={`wm-roll-number ${c.status === 'void' ? '' : assessment.state}`}>{c.total}<small>TOTAL</small></div><div className="wm-roll-copy"><div className="wm-section-heading"><strong>{c.characterName} <span className="wm-fine">· {c.skill}</span></strong><span className={`wm-badge ${assessment.state}`}>{status}</span></div><p className="wm-prose">{c.description}</p><p className="wm-fine">d20: {c.die} {c.modifier >= 0 ? '+' : '−'} {Math.abs(c.modifier)} · DC {c.finalDc ?? assessment.dc} · {c.kind} · finishes {dateLabel(c.endsAt)}</p>{c.status === 'pending' && assessment.state === 'potential' && <p className="wm-potential">Needs {assessment.needed} more DC reduction. Remaining aid could provide {assessment.remaining}; it must unlock before this action finishes.</p>}</div></article>;
}

const newCharacter = (): Omit<MiniCharacter, 'id' | 'status'> => ({ name: '', ancestry: '', heritage: '', classPrimary: '', classSecondary: '', level: 1 });
export function CharactersPage({ snapshot, execute, busy }: PageProps) {
  const [editing, setEditing] = useState<string | null>(null);
  const [form, setForm] = useState(newCharacter);
  const [open, setOpen] = useState(false);
  const [archive, setArchive] = useState<MiniCharacter | null>(null);
  return <><BackLink /><header className="wm-page-heading"><p className="wm-kicker">YOUR COMPANY</p><h1>Every legend starts somewhere.</h1><p className="wm-lede">A few details are enough to begin. These are your real registry characters, ready for portraits, backstories, and Foundry files as their stories grow.</p><button className="wm-button" onClick={() => { setEditing(null); setForm(newCharacter()); setOpen(true); }}><Plus size={18} /> Create a character</button></header>
    {open && <section className="wm-panel"><h2>{editing ? 'Edit your character' : 'Introduce your character'}</h2><form onSubmit={async e => { e.preventDefault(); if (await execute({ type: 'save_character', character: { ...form, ...(editing ? { id: editing } : {}) } })) setOpen(false); }}><div className="wm-form-grid">{([['name', 'Character name'], ['ancestry', 'Ancestry'], ['heritage', 'Heritage (optional)'], ['classPrimary', 'Primary class'], ['classSecondary', 'Secondary class (optional)']] as const).map(([key, label]) => <label className="wm-field" key={key}>{label}<input maxLength={100} required={['name', 'ancestry', 'classPrimary'].includes(key)} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<label className="wm-field">Level<input type="number" min={1} max={20} required value={form.level} onChange={e => setForm({ ...form, level: Number(e.target.value) })} /><small>Your level sets the base DC for future contributions. Existing rolls keep their original level.</small></label></div><div className="wm-actions"><button disabled={busy} className="wm-button" type="submit">{busy ? 'Saving…' : 'Save character'}</button><button disabled={busy} type="button" className="wm-button secondary" onClick={() => setOpen(false)}>Cancel</button></div></form></section>}
    <div className="wm-event-grid wm-board-section">{snapshot.characters.map(c => <article className="wm-character-card" key={c.id}><div className="wm-character-monogram">{c.name.slice(0, 1)}</div><span className="wm-badge">Level {c.level} · {c.status}</span><h2>{c.name}</h2><p>{[c.heritage, c.ancestry].filter(Boolean).join(' ')}<br />{[c.classPrimary, c.classSecondary].filter(Boolean).join(' / ')}</p><div className="wm-actions"><Link className="wm-button secondary" to={`/westmarch/characters/${c.id}`}>Character page <ArrowRight size={14} /></Link>{c.status === 'active' && <button className="wm-text-link" onClick={() => { setEditing(c.id); setForm(c); setOpen(true); }}>Edit</button>}{c.status === 'active' && <button className="wm-text-link" onClick={() => setArchive(c)}>Retire</button>}</div></article>)}</div>
    {!snapshot.characters.length && <section className="wm-empty"><Users size={32} /><h2>Your company is waiting to be formed.</h2><p>Create your first character above. No image or character-sheet upload is required.</p></section>}
    {archive && <section className="wm-confirm" role="alertdialog" aria-labelledby="wm-retire-title" aria-describedby="wm-retire-description"><h2 id="wm-retire-title">Retire {archive.name}?</h2><p id="wm-retire-description">Their history and existing time commitments remain. They will no longer be available for new contributions. This does not reroll or cancel any work.</p><div className="wm-actions"><button disabled={busy} className="wm-button danger" onClick={async () => { if (await execute({ type: 'archive_character', id: archive.id })) setArchive(null); }}>Confirm retirement</button><button disabled={busy} className="wm-button secondary" onClick={() => setArchive(null)}>Keep active</button></div></section>}
  </>;
}
