/*
  # Password-protected database administration and account bans

  - Adds ban state to user profiles and prevents clients from changing it directly.
  - Adds password-verified server commands for the hidden database admin panel.
  - Allows administrators to manage site roles, bans, characters, guilds, and lore.
  - Preserves historical games when their reward character is deleted.
*/

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS is_banned boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS banned_at timestamptz,
  ADD COLUMN IF NOT EXISTS banned_by text REFERENCES public.users(auth_user_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS users_is_banned_idx ON public.users(is_banned) WHERE is_banned = true;

DROP TRIGGER IF EXISTS prevent_client_admin_changes_trigger ON public.users;
DROP TRIGGER IF EXISTS prevent_client_loremaster_changes_trigger ON public.users;
DROP TRIGGER IF EXISTS prevent_client_moderation_changes_trigger ON public.users;

-- RLS controls which row a user can edit. Column privileges separately prevent
-- clients from ever writing protected moderation fields, including on their own row.
REVOKE INSERT, UPDATE ON public.users FROM anon, authenticated;
DO $$
DECLARE
  insert_columns text;
  update_columns text;
BEGIN
  SELECT string_agg(quote_ident(columns.column_name), ', ' ORDER BY columns.ordinal_position)
  INTO insert_columns
  FROM information_schema.columns
  WHERE columns.table_schema = 'public'
    AND columns.table_name = 'users'
    AND columns.column_name NOT IN (
      'id', 'is_admin', 'is_loremaster', 'is_banned', 'banned_at', 'banned_by'
    );

  SELECT string_agg(quote_ident(columns.column_name), ', ' ORDER BY columns.ordinal_position)
  INTO update_columns
  FROM information_schema.columns
  WHERE columns.table_schema = 'public'
    AND columns.table_name = 'users'
    AND columns.column_name NOT IN (
      'id', 'is_admin', 'is_loremaster', 'is_banned', 'banned_at', 'banned_by', 'created_at'
    );

  EXECUTE 'GRANT INSERT (' || insert_columns || ') ON public.users TO authenticated';
  EXECUTE 'GRANT UPDATE (' || update_columns || ') ON public.users TO authenticated';
END;
$$;

CREATE OR REPLACE FUNCTION public.is_user_banned(check_user_id text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    (SELECT users.is_banned FROM public.users WHERE users.auth_user_id = check_user_id),
    false
  );
$$;

CREATE OR REPLACE FUNCTION public.is_site_admin(check_user_id text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    (
      SELECT users.is_admin AND NOT users.is_banned
      FROM public.users
      WHERE users.auth_user_id = check_user_id
    ),
    false
  );
$$;

CREATE OR REPLACE FUNCTION public.is_loremaster(check_user_id text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    (
      SELECT (users.is_admin OR users.is_loremaster) AND NOT users.is_banned
      FROM public.users
      WHERE users.auth_user_id = check_user_id
    ),
    false
  );
$$;

CREATE TABLE IF NOT EXISTS public.db_admin_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id text,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.db_admin_audit_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.games
  ALTER COLUMN reward_character_id DROP NOT NULL;
ALTER TABLE public.games
  DROP CONSTRAINT IF EXISTS games_reward_character_id_fkey;
ALTER TABLE public.games
  ADD CONSTRAINT games_reward_character_id_fkey
  FOREIGN KEY (reward_character_id) REFERENCES public.characters(id) ON DELETE SET NULL;

CREATE OR REPLACE FUNCTION public.db_admin_password_matches(p_password text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SECURITY DEFINER
SET search_path = public, extensions, pg_temp
AS $$
  SELECT encode(digest(convert_to(COALESCE(p_password, ''), 'UTF8'), 'sha256'), 'hex')
    = 'd3e1af605cc84c4bf7da5bb5981293230d442490f575030a9d4359355c5d5f8f';
$$;

CREATE OR REPLACE FUNCTION public.require_db_admin_password(p_password text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF auth.uid() IS NOT NULL AND public.is_user_banned(auth.uid()::text) THEN
    RAISE EXCEPTION 'Banned accounts cannot use database administration';
  END IF;

  IF NOT public.db_admin_password_matches(p_password) THEN
    RAISE EXCEPTION 'Invalid database admin password';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.verify_db_admin_password_command(p_password text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  PERFORM public.require_db_admin_password(p_password);
  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_db_admin_snapshot_command(p_password text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  PERFORM public.require_db_admin_password(p_password);

  RETURN jsonb_build_object(
    'users', (
      SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'userId', users.auth_user_id,
        'username', users.username,
        'email', users.email,
        'avatar', COALESCE(NULLIF(users.avatar, ''), '/npc-placeholder.png'),
        'isAdmin', users.is_admin,
        'isLoremaster', users.is_loremaster,
        'isBanned', users.is_banned,
        'bannedAt', users.banned_at
      ) ORDER BY users.username), '[]'::jsonb)
      FROM public.users
    ),
    'characters', (
      SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'id', characters.id,
        'name', characters.name,
        'className', characters.class,
        'level', COALESCE(characters.level, 1),
        'ownerId', characters.user_id,
        'ownerName', COALESCE(users.username, 'Unknown user')
      ) ORDER BY characters.name), '[]'::jsonb)
      FROM public.characters
      LEFT JOIN public.users ON users.auth_user_id = characters.user_id
    ),
    'guilds', (
      SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'id', guilds.id,
        'name', guilds.name,
        'leaderId', guilds.leader_id,
        'leaderName', COALESCE(users.username, 'Unknown user'),
        'memberCount', COALESCE(guilds.member_count, 0)
      ) ORDER BY guilds.name), '[]'::jsonb)
      FROM public.guilds
      LEFT JOIN public.users ON users.auth_user_id = guilds.leader_id
    ),
    'loreEntries', (
      SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'id', lore_entries.id,
        'title', lore_entries.title,
        'status', lore_entries.status,
        'authorName', lore_entries.author_name
      ) ORDER BY lore_entries.title), '[]'::jsonb)
      FROM public.lore_entries
    )
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.set_db_admin_user_roles_command(
  p_password text,
  p_user_id text,
  p_is_admin boolean,
  p_is_loremaster boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  PERFORM public.require_db_admin_password(p_password);

  UPDATE public.users
  SET is_admin = p_is_admin,
      is_loremaster = p_is_loremaster,
      updated_at = now()
  WHERE auth_user_id = p_user_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'User not found'; END IF;

  INSERT INTO public.db_admin_audit_log (actor_id, action, entity_type, entity_id, details)
  VALUES (auth.uid()::text, 'set_roles', 'user', p_user_id, jsonb_build_object(
    'isAdmin', p_is_admin,
    'isLoremaster', p_is_loremaster
  ));
END;
$$;

CREATE OR REPLACE FUNCTION public.set_db_admin_user_ban_command(
  p_password text,
  p_user_id text,
  p_is_banned boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  PERFORM public.require_db_admin_password(p_password);

  UPDATE public.users
  SET is_banned = p_is_banned,
      banned_at = CASE WHEN p_is_banned THEN now() ELSE NULL END,
      banned_by = CASE WHEN p_is_banned THEN auth.uid()::text ELSE NULL END,
      is_online = CASE WHEN p_is_banned THEN false ELSE is_online END,
      updated_at = now()
  WHERE auth_user_id = p_user_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'User not found'; END IF;

  INSERT INTO public.db_admin_audit_log (actor_id, action, entity_type, entity_id, details)
  VALUES (auth.uid()::text, CASE WHEN p_is_banned THEN 'ban' ELSE 'unban' END, 'user', p_user_id, '{}'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_db_admin_content_command(
  p_password text,
  p_entity_type text,
  p_entity_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  deleted_name text;
BEGIN
  PERFORM public.require_db_admin_password(p_password);

  CASE p_entity_type
    WHEN 'character' THEN
      SELECT name INTO deleted_name FROM public.characters WHERE id = p_entity_id;
      IF deleted_name IS NULL THEN RAISE EXCEPTION 'Character not found'; END IF;

      DELETE FROM public.game_applications
      WHERE p_entity_id = ANY(character_ids) AND cardinality(character_ids) = 1;
      UPDATE public.game_applications
      SET character_ids = array_remove(character_ids, p_entity_id), updated_at = now()
      WHERE p_entity_id = ANY(character_ids);
      DELETE FROM public.characters WHERE id = p_entity_id;

    WHEN 'guild' THEN
      SELECT name INTO deleted_name FROM public.guilds WHERE id = p_entity_id;
      IF deleted_name IS NULL THEN RAISE EXCEPTION 'Guild not found'; END IF;
      DELETE FROM public.guilds WHERE id = p_entity_id;

    WHEN 'lore' THEN
      SELECT title INTO deleted_name FROM public.lore_entries WHERE id = p_entity_id;
      IF deleted_name IS NULL THEN RAISE EXCEPTION 'Lore entry not found'; END IF;
      DELETE FROM public.lore_entries WHERE id = p_entity_id;

    ELSE
      RAISE EXCEPTION 'Unsupported database admin entity type';
  END CASE;

  INSERT INTO public.db_admin_audit_log (actor_id, action, entity_type, entity_id, details)
  VALUES (auth.uid()::text, 'delete', p_entity_type, p_entity_id::text, jsonb_build_object('name', deleted_name));
END;
$$;

REVOKE ALL ON FUNCTION public.is_user_banned(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.db_admin_password_matches(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.require_db_admin_password(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.verify_db_admin_password_command(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_db_admin_snapshot_command(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_db_admin_user_roles_command(text, text, boolean, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_db_admin_user_ban_command(text, text, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_db_admin_content_command(text, text, uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.verify_db_admin_password_command(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_db_admin_snapshot_command(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_db_admin_user_roles_command(text, text, boolean, boolean) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_db_admin_user_ban_command(text, text, boolean) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.delete_db_admin_content_command(text, text, uuid) TO anon, authenticated;
